version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - ai-network
    depends_on:
      - ollama
      - qdrant

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - ai-network

  helper:
    build:
      context: ./helper
      dockerfile: Dockerfile
      args:
        - REQUIREMENTS_PATH=../../requirements.txt
    volumes:
      - ../scripts:/app/scripts
      - ../data:/app/data
      - ../config.json:/app/config.json
      - ../requirements.txt:/app/requirements.txt
    networks:
      - ai-network
    depends_on:
      - ollama
      - qdrant
      - n8n

networks:
  ai-network:
    driver: bridge

volumes:
  n8n_data:
  ollama_data:
  qdrant_data:
